### ISSUE TITLE
No submodule mapping found

### ISSUE THREAD

**Issue by cassdalton** [jlezama/OrthogonalLowrankEmbedding#1]
Instructions in OrthogonalLowrankEmbedding/pytorch_OLE/README.md say to clone the repo via 
`git clone --recursive https://github.com/jlezama/OrthogonalLowrankEmbedding.git`
but that results in 
fatal: no submodule mapping found in .gitmodules for path 'pytorch_OLE/utils/progress'

**Comment by jlezama** [comment]
Fixed. Thank you!
